sudo: required

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.17.0

before_install:
  # docker-compose upgrade
  - sudo rm -f /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  # docker upgrade
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  # build an run as in prod
  - make build-docker
  - docker-compose -f ./docker-compose.yml up -d
  - sleep 120 ; docker-compose logs

script:
  - docker-compose ps
  # just test there is 2 running containers, that is not a lot but that's already it!
  - NB_CONTAINERS=$(docker-compose ps | grep " Up " | wc -l)
  - test $NB_CONTAINERS = 2

notifications:
  email:
    recipients:
      - ezpaarse-team@googlegroups.com
      - dominique.lechaudel@gmail.com
    on_success: change
    on_failure: always
  slack:
    secure: p/7J6LXqmmkQBaJ4q3KUibZgzKevo+ExTOiY+O4UQQa597dbK72gMWp+RKYVnfrhoMfTPD8oS8JG9nu74s6/mKHAtVc/g0qPH549tHpFC1DqD7G0TNUZxNV1tiWXkNbSPe59tkrn9R95azIA52cDXA1i9cguOYnCLysmEPUMQwU=
